// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderItemsNew struct {
	ID        int32              `json:"id"`
	OrderID   int32              `json:"order_id"`
	ProductID int32              `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	Price     int32              `json:"price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrderNew struct {
	ID         int32              `json:"id"`
	CustomerID int32              `json:"customer_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Price     int32              `json:"price"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
