// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	ListProducts(ctx context.Context) ([]Product, error)
	ProductById(ctx context.Context, id int32) (Product, error)
}

var _ Querier = (*Queries)(nil)
